services:
  postgres:
    image: postgres:16
    container_name: food-app-postgres
    restart: unless-stopped
    
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secure_pass_123
      POSTGRES_DB: food_app_db
    
    ports:
      - "5432:5432"
    
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d food_app_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    
    networks:
      - food-app-network

volumes:
  postgres_data:

networks:
  food-app-network:
    driver: bridge
